(()=>{"use strict";
const $=id=>document.getElementById(id),C=()=>window.ACADEMIA_CONTENT||[],cfg=window.OM_SUPABASE||{};
const db=window.supabase&&cfg.url?window.supabase.createClient(cfg.url,cfg.publishableKey):null;
let S={profile:null,completed:[],xp:0,badges:[]},cur=0,sl=0,tab="lesson",cp={},qi=0,qs=0;
try{const x=localStorage.getItem("oemFinal");if(x)S=JSON.parse(x)}catch(e){}
const save=()=>{try{localStorage.setItem("oemFinal",JSON.stringify(S))}catch(e){}};
const admin=()=>S.profile?.access_role==="ADMIN";
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const unlocked=i=>{if(admin())return true;if(!S.profile?.admission_date)return i===0;const a=new Date(S.profile.admission_date+"T00:00:00"),n=new Date();n.setHours(0,0,0,0);return Math.floor((n-a)/86400000)>=i*7};
async function sync(){if(!db||!S.profile)return;const r=await db.rpc("academia_progress",{p_profile_id:S.profile.profile_id});if(r.error)return;S.completed=[];S.xp=0;(r.data||[]).forEach(x=>{if(x.status==="completed"){S.completed.push(+x.track_number-1);S.xp+=+(x.xp||0)}});S.completed=[...new Set(S.completed)].sort((a,b)=>a-b);save()}
function header(){$("headerXp").textContent=S.profile?S.xp+" XP":"";$("loginBtn").textContent=S.profile?"PERFIL":"ENTRAR";$("nav").innerHTML=S.profile?`<button data-h>INÍCIO</button><button data-h>JORNADA</button><button data-c>CERTIFICADOS</button>${admin()?`<button data-a>EVOLUÇÃO</button>`:""}`:"";$("nav [data-h]")?.addEventListener("click",home);$("nav [data-c]")?.addEventListener("click",certs);$("nav [data-a]")?.addEventListener("click",adminDash)}
function groups(){return[["01","FUNDAMENTOS",0,5],["02","OPERAÇÃO SEGURA",5,10],["03","RISCOS DA UFV",10,15],["04","CULTURA E COMPORTAMENTO",15,20],["05","GUARDIÃO",20,21]]}
function nextIndex(){return C().findIndex((_,i)=>!S.completed.includes(i))}
function home(){let n=nextIndex();if(n<0)n=0;$("app").innerHTML=`<section class=field><div class=hero><div><span class=eyebrow>ACADEMIA DE SEGURANÇA O&M SOLAR</span><h1>GUARDIÕES<br>DA USINA</h1><p>Uma jornada de segurança em formato de jogo. Avance pela trilha, complete os treinamentos, conquiste XP e torne-se um Guardião.</p><div class=actions><button id=heroStart class=primary>${S.profile?"CONTINUAR JORNADA":"ENTRAR PARA COMEÇAR"} →</button><button id=how class=secondary>COMO FUNCIONA</button></div><div class=stats><div class=stat><small>XP</small><strong>${S.xp}</strong></div><div class=stat><small>NÍVEL</small><strong>${Math.floor(S.xp/100)+1}</strong></div><div class=stat><small>PROGRESSO</small><strong>${S.completed.length}/21</strong></div></div></div><img src=mascote-3d.png alt="Guardião da Usina"></div><div class=journey><div class=journeyHead><div><span class=eyebrow>TRILHA DE APRENDIZAGEM</span><h2>Seu caminho até Guardião</h2></div><span>5 fases • 21 treinamentos</span></div>${groups().map(g=>phase(g)).join("")}<div class=next><div><small>${S.profile?"PRÓXIMA ETAPA":"COMECE AQUI"}</small><b>${esc(C()[n].title)}</b></div><button id=nextBtn class=primary>${S.profile?"CONTINUAR":"ENTRAR"} →</button></div></div></section>`;$("heroStart").onclick=()=>S.profile?openGame(n):loginOpen();$("nextBtn").onclick=()=>S.profile?openGame(n):loginOpen();$("how").onclick=()=>alert("A jornada libera um treinamento a cada 7 dias. Cada treinamento possui 15 etapas, 3 checkpoints, um caso prático e uma prova final de 10 questões. Aprovação: 70%.");document.querySelectorAll("[data-node]").forEach(b=>b.onclick=()=>openGame(+b.dataset.node))}
function phase(g){let out=`<div class=phase><div class=phaseTitle><b>${g[0]} • ${g[1]}</b><span>${g[3]-g[2]} treinamentos</span></div><div class=path>`;for(let i=g[2];i<g[3];i++){let d=S.completed.includes(i),u=unlocked(i),c=i===nextIndex();out+=`<div class="node ${d?"done":c?"current":!u?"locked":""}"><button data-node=${i} ${u?"":"disabled"}>${d?"✓":i+1}</button><small>${esc(C()[i].title.split(" – ")[0].slice(0,19))}</small></div>`}return out+"</div></div>"}
function loginOpen(){$("loginModal").classList.add("show");$("loginError").textContent="";setTimeout(()=>$("mat").focus(),50)}
function loginClose(){$("loginModal").classList.remove("show")}
async function login(){if(!db){$("loginError").textContent="Banco não configurado.";return}let m=$("mat").value.trim(),p=$("pin").value.trim();if(!m||!p){$("loginError").textContent="Informe matrícula e PIN.";return}$("loginError").textContent="Validando…";let r=await db.rpc("academia_login",{p_matricula:m,p_pin:p});if(r.error||!r.data?.length){$("loginError").textContent="Matrícula ou PIN inválidos.";return}S.profile=r.data[0];save();loginClose();await sync();header();home()}
function openGame(i){if(!S.profile){loginOpen();return}if(!unlocked(i)){alert("Este treinamento ainda não foi liberado. A jornada avança uma etapa por semana.");return}cur=i;sl=0;tab="lesson";cp={};qi=0;qs=0;$("gameModal").classList.add("show");renderGame()}
function gameClose(){$("gameModal").classList.remove("show")}
function renderGame(){let t=C()[cur];$("gameXp").textContent=S.xp+" XP";$("head").innerHTML=`<div class=head><img src=${t.slides[sl].image}><div><span class=eyebrow>TREINAMENTO ${String(t.id).padStart(2,"0")} • ${esc(t.phase)}</span><h2>${esc(t.title)}</h2><p>${esc(t.description)}</p></div></div>`;$("tracks").innerHTML=C().map((x,i)=>`<div class="track ${i===cur?"active":""} ${S.completed.includes(i)?"done":""} ${unlocked(i)?"":"locked"}" data-t=${i}><span class=trackNum>${S.completed.includes(i)?"✓":i+1}</span><span>${esc(x.title)}</span></div>`).join("");document.querySelectorAll("[data-t]").forEach(b=>b.onclick=()=>openGame(+b.dataset.t));document.querySelectorAll("[data-tab]").forEach(b=>{b.classList.toggle("active",b.dataset.tab===tab);b.onclick=()=>{tab=b.dataset.tab;renderGame()}});if(tab==="lesson")slideView();else if(tab==="case")caseView();else if(tab==="refs")refsView();else examView();let p=tab==="exam"?100:Math.round((sl+1)/15*100);$("pct").textContent=p+"%";$("bar").style.width=p+"%";$("gameModal").style.setProperty("--p",p+"%");$("gameModal").querySelector(".ring").style.setProperty("--p",p+"%");$("outline").innerHTML=t.slides.map((s,i)=>`<div class="outline ${i===sl?"active":""}">${i+1}. ${esc(s.title)}</div>`).join("")}
function slideView(){let s=C()[cur].slides[sl];$("lesson").innerHTML=`<div class=slide><img src=${s.image}><div class=body><span class=eyebrow>ETAPA ${sl+1} DE 15</span><h3>${esc(s.title)}</h3><p>${esc(s.body)}</p><ul>${s.bullets.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>${s.checkpoint?`<div class=checkpoint><b>⚡ CHECKPOINT</b><p>${esc(s.checkpointQuestion)}</p><button class=choice data-c=1>${esc(s.checkpointAnswer)}</button><button class=choice data-c=0>Continuar sem aplicar o controle.</button></div>`:""}</div></div>`;document.querySelectorAll("[data-c]").forEach(b=>b.onclick=()=>{if(b.dataset.c==="1"){cp[sl]=true;b.classList.add("ok")}else b.classList.add("bad")})}
function next(){if(tab==="lesson"){let s=C()[cur].slides[sl];if(s.checkpoint&&!cp[sl])return alert("Conclua o checkpoint antes de avançar.");if(sl<14){sl++;renderGame()}else{tab="case";renderGame()}}else if(tab==="case"||tab==="refs"){tab="exam";renderGame()}else examView()}
function caseView(){let c=C()[cur].case;$("lesson").innerHTML=`<div class=case><span class=eyebrow>DESAFIO DE CAMPO</span><h2>${esc(c.title)}</h2><p>${esc(c.scenario)}</p>${c.options.map((x,i)=>`<button class=choice data-ca=${i}>${esc(x)}</button>`).join("")}<div id=caseMsg></div></div>`;document.querySelectorAll("[data-ca]").forEach(b=>b.onclick=()=>{let ok=+b.dataset.ca===c.correct;document.querySelectorAll("[data-ca]").forEach(x=>x.disabled=true);b.classList.add(ok?"ok":"bad");$("caseMsg").innerHTML=ok?"<p style='color:var(--green)'>✓ Caso resolvido.</p><button class=primary id=goExam>IR PARA A AVALIAÇÃO →</button>":"<p style='color:var(--red)'>✕ Decisão insegura. Revise o cenário.</p>";if(ok)$("goExam").onclick=()=>{tab="exam";renderGame()}})}
function refsView(){let t=C()[cur];$("lesson").innerHTML=`<div class=case><span class=eyebrow>BASE TÉCNICA</span><h2>Referências</h2><ul>${t.references.map(x=>`<li>${esc(x)}</li>`).join("")}</ul><p>Instrução interna. Na execução real, prevalecem as referências vigentes e os procedimentos aplicáveis.</p></div>`}
function examView(){let q=C()[cur].questions[qi];$("lesson").innerHTML=`<div class=exam><span class=eyebrow>AVALIAÇÃO FINAL • ${qi+1}/10</span><h2>${esc(q.q)}</h2>${q.options.map((x,i)=>`<button class=choice data-e=${i}>${esc(x)}</button>`).join("")}<p>Aprovação mínima: 70%. Abaixo disso, o treinamento reinicia desde a etapa 1.</p></div>`;document.querySelectorAll("[data-e]").forEach(b=>b.onclick=()=>{if(+b.dataset.e===q.correct)qs++;qi++;qi<10?examView():finish()})}
async function finish(){let score=qs*10;if(score<70){$("lesson").innerHTML=`<div class=exam><div class=score style='color:var(--red)'>${score}%</div><h2>REPROVADO</h2><p>O treinamento será reiniciado desde a etapa 1.</p><button class=primary id=redo>RECOMEÇAR →</button></div>`;$("redo").onclick=()=>{sl=0;qi=0;qs=0;tab="lesson";renderGame()};return}let t=C()[cur],r=await db.rpc("academia_complete_training",{p_profile_id:S.profile.profile_id,p_track_number:t.id,p_certificate_code:"OEM-"+t.id+"-"+Date.now().toString(36),p_score:score});if(r.error)return alert(r.error.message);S.completed=[...new Set([...S.completed,cur])];S.xp+=100;S.badges=[...new Set([...(S.badges||[]),t.badge])];save();header();$("lesson").innerHTML=`<div class=exam><div class=score>${score}%</div><h2>✓ TREINAMENTO CONCLUÍDO</h2><p>+100 XP • Badge desbloqueada • Certificado liberado.</p><button class=primary id=certNow>VER CERTIFICADO →</button></div>`;$("certNow").onclick=()=>certificate(cur)}
function certificate(i){let t=C()[i],w=open("","_blank");if(!w)return;w.document.write(`<body style="background:#07131d;color:#fff;font:16px Arial;padding:50px"><div style="max-width:850px;margin:auto;padding:55px;text-align:center;border:2px solid #47728d;background:#0b1c2a"><p>ACADEMIA DE SEGURANÇA O&M SOLAR</p><h1>CERTIFICADO DE PARTICIPAÇÃO</h1><h2>${esc(t.title)}</h2><h2>${esc(S.profile.full_name)}</h2><p>Matrícula: ${esc(S.profile.employee_code)}</p><p>Cargo: ${esc(S.profile.job_title||"—")} • Unidade: ${esc(S.profile.plant||"—")}</p><p>${new Date().toLocaleDateString("pt-BR")}</p><hr><p>Participação e instrução interna. Sem assinatura e sem validade legal.</p></div>`);w.document.close()}
function certs(){$("app").innerHTML=`<section class=field><span class=eyebrow>CONQUISTAS</span><h1>Certificados</h1><div class=journey>${S.completed.length?S.completed.map(i=>`<div class=next><div><small>CONCLUÍDO</small><b>${esc(C()[i].title)}</b></div><button class=primary data-cert=${i>999?-1:i}>ABRIR →</button></div>`).join(""):"<p>Você ainda não possui certificados.</p>"}</div></section>`;document.querySelectorAll("[data-cert]").forEach(b=>b.onclick=()=>certificate(+b.dataset.cert))}
async function adminDash(){if(!admin())return;let r=await db.rpc("academia_admin_dashboard",{p_profile_id:S.profile.profile_id});if(r.error)return alert(r.error.message);let d=r.data||{};$("app").innerHTML=`<section class=field><span class=eyebrow>ADMIN 101 • EVOLUÇÃO</span><h1>Evolução da equipe</h1><div class=stats><div class=stat><small>COLABORADORES</small><strong>${d.collaborators||0}</strong></div><div class=stat><small>CONCLUSÕES</small><strong>${d.completed||0}</strong></div><div class=stat><small>MÉDIA</small><strong>${d.avg_score||0}%</strong></div><div class=stat><small>CERTIFICADOS</small><strong>${d.certificates||0}</strong></div></div><div class=journey>${(d.people||[]).map(p=>`<div class=next><div><b>${esc(p.full_name)}</b><small>${esc(p.employee_code)} • ${esc(p.job_title||"")}</small></div><b>${p.completed||0}/21 • ${p.avg_score||0}% • ${p.xp||0} XP</b></div>`).join("")}</div></section>`}

$("brand").onclick=home;$("loginBtn").onclick=()=>S.profile?alert("Você está logado como "+S.profile.full_name):loginOpen();$("loginClose").onclick=loginClose;$("loginForm").onsubmit=e=>{e.preventDefault();login()};$("gameClose").onclick=gameClose;$("continue").onclick=next;$("mat").onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();$("pin").focus()}};window.onkeydown=e=>{if(e.key==="Escape"){loginClose();gameClose()}};
header();if(S.profile)sync().then(()=>{header();home()});else home();
})();